version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: group
    command: [ "mongod", "--replSet", "rs0" ] # Enables replica set
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
