import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header"; // Adjust the path if necessary


// Import DM Sans font
import { DM_Sans } from 'next/font/google';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// Initialize the font with desired options
const dmSans = DM_Sans({
  subsets: ['latin'], // Specify the character subsets you need
  weight: ['400', '500', '700'], // Include the font weights you plan to use
  style: ['normal', 'italic'], // Include styles if needed
  variable: '--font-dm-sans', // Define a CSS variable for the font
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={dmSans.variable}>
      <body>
        {/* Header */}
        <Header
          logoText="MyApp"
          navLinks={[
            { name: 'Home', href: '/' },
            { name: 'My Groups', href: '/my-groups' },
            { name: 'About', href: '/about' },
          ]}
          groupCount={19}
        />

        {/* Main Content */}
        <main >
          {children}
        </main>

        {/* Optional: Footer Component */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}