import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header"; // Adjust the path if necessary


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header
          logoText="MyApp"
          navLinks={[
            { name: 'Home', href: '/' },
            { name: 'My Groups', href: '/my-groups' },
            { name: 'About', href: '/about' },
          ]}
          groupCount={19}
        />

        {/* Main Content */}
        <main >
          {children}
        </main>

        {/* Optional: Footer Component */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}